# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150)),
                ('blog_content', models.TextField()),
                ('blog_date_created', models.CharField(max_length=35)),
                ('blog_date_modified', models.CharField(max_length=35)),
                ('blog_timezone_date_modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='UserExtraFeatures',
            fields=[
                ('blog_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blog_last_posted_time', models.DateTimeField()),
                ('user_can_post', models.BooleanField()),
            ],
            options={
                'db_table': 'user_extra_features',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
