# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tt_django_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_time_since_post',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_time_since_post_creation',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_timezone_date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
